// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from 'viem'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'
import '@nomicfoundation/hardhat-viem/types'

export interface IERC777Sender$Type {
  _format: 'hh-sol-artifact-1',
  contractName: 'IERC777Sender',
  sourceName: '@openzeppelin/contracts/token/ERC777/IERC777Sender.sol',
  abi: [
    {
      inputs: [
        {
          internalType: 'address',
          name: 'operator',
          type: 'address'
        },
        {
          internalType: 'address',
          name: 'from',
          type: 'address'
        },
        {
          internalType: 'address',
          name: 'to',
          type: 'address'
        },
        {
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256'
        },
        {
          internalType: 'bytes',
          name: 'userData',
          type: 'bytes'
        },
        {
          internalType: 'bytes',
          name: 'operatorData',
          type: 'bytes'
        }
      ],
      name: 'tokensToSend',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }
  ],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {}
}

declare module '@nomicfoundation/hardhat-viem/types' {
  export function deployContract (
    contractName: 'IERC777Sender',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC777Sender$Type['abi']>>
  export function deployContract (
    contractName: '@openzeppelin/contracts/token/ERC777/IERC777Sender.sol:IERC777Sender',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC777Sender$Type['abi']>>

  export function sendDeploymentTransaction (
    contractName: 'IERC777Sender',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC777Sender$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>
  export function sendDeploymentTransaction (
    contractName: '@openzeppelin/contracts/token/ERC777/IERC777Sender.sol:IERC777Sender',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC777Sender$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>

  export function getContractAt (
    contractName: 'IERC777Sender',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC777Sender$Type['abi']>>
  export function getContractAt (
    contractName: '@openzeppelin/contracts/token/ERC777/IERC777Sender.sol:IERC777Sender',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC777Sender$Type['abi']>>
}
