// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { ERC777$Type } from './ERC777'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['ERC777']: ERC777$Type;
    ['@openzeppelin/contracts/token/ERC777/ERC777.sol:ERC777']: ERC777$Type;
  }

  interface ContractTypesMap {
    ['ERC777']: GetContractReturnType<ERC777$Type['abi']>;
    ['@openzeppelin/contracts/token/ERC777/ERC777.sol:ERC777']: GetContractReturnType<ERC777$Type['abi']>;
  }
}
