// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Asset$Type } from "./Asset";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Asset"]: Asset$Type;
    ["contracts/Asset.sol:Asset"]: Asset$Type;
  }

  interface ContractTypesMap {
    ["Asset"]: GetContractReturnType<Asset$Type["abi"]>;
    ["contracts/Asset.sol:Asset"]: GetContractReturnType<Asset$Type["abi"]>;
  }
}
