// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleEnhancedCoin$Type } from "./ExampleEnhancedCoin";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleEnhancedCoin"]: ExampleEnhancedCoin$Type;
    ["contracts/utils/ExampleEnhancedCoin.sol:ExampleEnhancedCoin"]: ExampleEnhancedCoin$Type;
  }

  interface ContractTypesMap {
    ["ExampleEnhancedCoin"]: GetContractReturnType<ExampleEnhancedCoin$Type["abi"]>;
    ["contracts/utils/ExampleEnhancedCoin.sol:ExampleEnhancedCoin"]: GetContractReturnType<ExampleEnhancedCoin$Type["abi"]>;
  }
}
