// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ShortStrings$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ShortStrings",
  "sourceName": "@openzeppelin/contracts/utils/ShortStrings.sol",
  "abi": [
    {
      "inputs": [],
      "name": "InvalidShortString",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "str",
          "type": "string"
        }
      ],
      "name": "StringTooLong",
      "type": "error"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122028e8d02a4cdd8b49d4220669bf23d4e574c1278e275a60af45f79afb230f5f8264736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122028e8d02a4cdd8b49d4220669bf23d4e574c1278e275a60af45f79afb230f5f8264736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ShortStrings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ShortStrings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ShortStrings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ShortStrings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ShortStrings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ShortStrings$Type["abi"]>>;
}
