// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Bytes$Type } from "./Bytes";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Bytes"]: Bytes$Type;
    ["@openzeppelin/contracts/utils/Bytes.sol:Bytes"]: Bytes$Type;
  }

  interface ContractTypesMap {
    ["Bytes"]: GetContractReturnType<Bytes$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Bytes.sol:Bytes"]: GetContractReturnType<Bytes$Type["abi"]>;
  }
}
