// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Bytes$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Bytes",
  "sourceName": "@openzeppelin/contracts/utils/Bytes.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200b5c201fbc344a4298c94a1dbf06a2e45025d574c3b8e4fac9f6816850d4c16064736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200b5c201fbc344a4298c94a1dbf06a2e45025d574c3b8e4fac9f6816850d4c16064736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Bytes",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Bytes.sol:Bytes",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Bytes",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Bytes$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Bytes.sol:Bytes",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Bytes$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Bytes",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Bytes.sol:Bytes",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;
}
