// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IOrgan$Type } from "./IOrgan";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IOrgan"]: IOrgan$Type;
    ["contracts/IOrgan.sol:IOrgan"]: IOrgan$Type;
  }

  interface ContractTypesMap {
    ["IOrgan"]: GetContractReturnType<IOrgan$Type["abi"]>;
    ["contracts/IOrgan.sol:IOrgan"]: GetContractReturnType<IOrgan$Type["abi"]>;
  }
}
