// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IOrgan$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IOrgan",
  "sourceName": "contracts/IOrgan.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "address",
              "name": "addr",
              "type": "address"
            },
            {
              "internalType": "string",
              "name": "cid",
              "type": "string"
            }
          ],
          "internalType": "struct CoreLibrary.Entry[]",
          "name": "entries",
          "type": "tuple[]"
        }
      ],
      "name": "addEntries",
      "outputs": [
        {
          "internalType": "uint256[]",
          "name": "indexes",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "permissionAddress",
          "type": "address"
        },
        {
          "internalType": "bytes2",
          "name": "permissionValue",
          "type": "bytes2"
        }
      ],
      "name": "addPermission",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "getEntry",
      "outputs": [
        {
          "components": [
            {
              "internalType": "address",
              "name": "addr",
              "type": "address"
            },
            {
              "internalType": "string",
              "name": "cid",
              "type": "string"
            }
          ],
          "internalType": "struct CoreLibrary.Entry",
          "name": "entry",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "addr",
          "type": "address"
        }
      ],
      "name": "getEntryIndexForAddress",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getOrgan",
      "outputs": [
        {
          "internalType": "string",
          "name": "cid",
          "type": "string"
        },
        {
          "internalType": "uint256",
          "name": "permissionsLength",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "entriesLength",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "entriesCount",
          "type": "uint256"
        },
        {
          "internalType": "bytes4",
          "name": "interfaceId",
          "type": "bytes4"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "getPermission",
      "outputs": [
        {
          "internalType": "address",
          "name": "addr",
          "type": "address"
        },
        {
          "internalType": "bytes2",
          "name": "perms",
          "type": "bytes2"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "addr",
          "type": "address"
        }
      ],
      "name": "getPermissions",
      "outputs": [
        {
          "internalType": "bytes2",
          "name": "perms",
          "type": "bytes2"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address[]",
          "name": "procedures",
          "type": "address[]"
        },
        {
          "internalType": "bytes2[]",
          "name": "permissions",
          "type": "bytes2[]"
        },
        {
          "internalType": "string",
          "name": "cid",
          "type": "string"
        },
        {
          "internalType": "address",
          "name": "trustedForwarder",
          "type": "address"
        }
      ],
      "name": "initialize",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256[]",
          "name": "indexes",
          "type": "uint256[]"
        }
      ],
      "name": "removeEntries",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "permissionAddress",
          "type": "address"
        }
      ],
      "name": "removePermission",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        },
        {
          "components": [
            {
              "internalType": "address",
              "name": "addr",
              "type": "address"
            },
            {
              "internalType": "string",
              "name": "cid",
              "type": "string"
            }
          ],
          "internalType": "struct CoreLibrary.Entry",
          "name": "entry",
          "type": "tuple"
        }
      ],
      "name": "replaceEntry",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "oldPermission",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "newPermission",
          "type": "address"
        },
        {
          "internalType": "bytes2",
          "name": "newPermissionValue",
          "type": "bytes2"
        }
      ],
      "name": "replacePermission",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "cid",
          "type": "string"
        }
      ],
      "name": "updateCid",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IOrgan",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IOrgan$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/IOrgan.sol:IOrgan",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IOrgan$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IOrgan",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IOrgan$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/IOrgan.sol:IOrgan",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IOrgan$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IOrgan",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IOrgan$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/IOrgan.sol:IOrgan",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IOrgan$Type["abi"]>>;
}
