// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MetaGasStation$Type } from "./MetaGasStation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MetaGasStation"]: MetaGasStation$Type;
    ["contracts/MetaGasStation.sol:MetaGasStation"]: MetaGasStation$Type;
  }

  interface ContractTypesMap {
    ["MetaGasStation"]: GetContractReturnType<MetaGasStation$Type["abi"]>;
    ["contracts/MetaGasStation.sol:MetaGasStation"]: GetContractReturnType<MetaGasStation$Type["abi"]>;
  }
}
