// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ERC2771Recipient$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ERC2771Recipient",
  "sourceName": "contracts/MetaGasStation.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "forwarder",
          "type": "address"
        }
      ],
      "name": "isTrustedForwarder",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "trustedForwarder",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ERC2771Recipient",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC2771Recipient$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/MetaGasStation.sol:ERC2771Recipient",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC2771Recipient$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ERC2771Recipient",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC2771Recipient$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/MetaGasStation.sol:ERC2771Recipient",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC2771Recipient$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ERC2771Recipient",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC2771Recipient$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/MetaGasStation.sol:ERC2771Recipient",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC2771Recipient$Type["abi"]>>;
}
