// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Arrays$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Arrays",
  "sourceName": "@openzeppelin/contracts/utils/Arrays.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c79b323a39cd8c032a41fc1b888262ccb83fca42738f046c81fe4499755e086164736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c79b323a39cd8c032a41fc1b888262ccb83fca42738f046c81fe4499755e086164736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Arrays",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Arrays.sol:Arrays",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Arrays",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Arrays$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Arrays.sol:Arrays",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Arrays$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Arrays",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Arrays.sol:Arrays",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;
}
