// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { GsnUtils$Type } from './GsnUtils'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['GsnUtils']: GsnUtils$Type;
    ['@opengsn/contracts/src/utils/GsnUtils.sol:GsnUtils']: GsnUtils$Type;
  }

  interface ContractTypesMap {
    ['GsnUtils']: GetContractReturnType<GsnUtils$Type['abi']>;
    ['@opengsn/contracts/src/utils/GsnUtils.sol:GsnUtils']: GetContractReturnType<GsnUtils$Type['abi']>;
  }
}
