// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from 'viem'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'
import '@nomicfoundation/hardhat-viem/types'

export interface GsnUtils$Type {
  _format: 'hh-sol-artifact-1',
  contractName: 'GsnUtils',
  sourceName: '@opengsn/contracts/src/utils/GsnUtils.sol',
  abi: [],
  bytecode: '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122060e260c629950aa364cf05ae984162704eb2cf9a5e0c2b530a34edf6f57a607f64736f6c63430008130033',
  deployedBytecode: '0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122060e260c629950aa364cf05ae984162704eb2cf9a5e0c2b530a34edf6f57a607f64736f6c63430008130033',
  linkReferences: {},
  deployedLinkReferences: {}
}

declare module '@nomicfoundation/hardhat-viem/types' {
  export function deployContract (
    contractName: 'GsnUtils',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<GsnUtils$Type['abi']>>
  export function deployContract (
    contractName: '@opengsn/contracts/src/utils/GsnUtils.sol:GsnUtils',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<GsnUtils$Type['abi']>>

  export function sendDeploymentTransaction (
    contractName: 'GsnUtils',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<GsnUtils$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>
  export function sendDeploymentTransaction (
    contractName: '@opengsn/contracts/src/utils/GsnUtils.sol:GsnUtils',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<GsnUtils$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>

  export function getContractAt (
    contractName: 'GsnUtils',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<GsnUtils$Type['abi']>>
  export function getContractAt (
    contractName: '@opengsn/contracts/src/utils/GsnUtils.sol:GsnUtils',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<GsnUtils$Type['abi']>>
}
