// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NominationProcedure$Type } from "./NominationProcedure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NominationProcedure"]: NominationProcedure$Type;
    ["contracts/procedures/Nomination.sol:NominationProcedure"]: NominationProcedure$Type;
  }

  interface ContractTypesMap {
    ["NominationProcedure"]: GetContractReturnType<NominationProcedure$Type["abi"]>;
    ["contracts/procedures/Nomination.sol:NominationProcedure"]: GetContractReturnType<NominationProcedure$Type["abi"]>;
  }
}
