// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LowLevelCall$Type } from "./LowLevelCall";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LowLevelCall"]: LowLevelCall$Type;
    ["@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall"]: LowLevelCall$Type;
  }

  interface ContractTypesMap {
    ["LowLevelCall"]: GetContractReturnType<LowLevelCall$Type["abi"]>;
    ["@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall"]: GetContractReturnType<LowLevelCall$Type["abi"]>;
  }
}
