// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LowLevelCall$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LowLevelCall",
  "sourceName": "@openzeppelin/contracts/utils/LowLevelCall.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220e8b0141aed534dbb5cc716a01fd3dd9743959fd52a529af21797e1923c4a3bc164736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220e8b0141aed534dbb5cc716a01fd3dd9743959fd52a529af21797e1923c4a3bc164736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LowLevelCall",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LowLevelCall",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LowLevelCall$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LowLevelCall$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LowLevelCall",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/LowLevelCall.sol:LowLevelCall",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LowLevelCall$Type["abi"]>>;
}
