// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { IERC777Recipient$Type } from './IERC777Recipient'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['IERC777Recipient']: IERC777Recipient$Type;
    ['@openzeppelin/contracts/token/ERC777/IERC777Recipient.sol:IERC777Recipient']: IERC777Recipient$Type;
  }

  interface ContractTypesMap {
    ['IERC777Recipient']: GetContractReturnType<IERC777Recipient$Type['abi']>;
    ['@openzeppelin/contracts/token/ERC777/IERC777Recipient.sol:IERC777Recipient']: GetContractReturnType<IERC777Recipient$Type['abi']>;
  }
}
