// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { IERC777$Type } from './IERC777'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['IERC777']: IERC777$Type;
    ['@openzeppelin/contracts/token/ERC777/IERC777.sol:IERC777']: IERC777$Type;
  }

  interface ContractTypesMap {
    ['IERC777']: GetContractReturnType<IERC777$Type['abi']>;
    ['@openzeppelin/contracts/token/ERC777/IERC777.sol:IERC777']: GetContractReturnType<IERC777$Type['abi']>;
  }
}
