// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { IRelayHub$Type } from './IRelayHub'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['IRelayHub']: IRelayHub$Type;
    ['@opengsn/contracts/src/interfaces/IRelayHub.sol:IRelayHub']: IRelayHub$Type;
  }

  interface ContractTypesMap {
    ['IRelayHub']: GetContractReturnType<IRelayHub$Type['abi']>;
    ['@opengsn/contracts/src/interfaces/IRelayHub.sol:IRelayHub']: GetContractReturnType<IRelayHub$Type['abi']>;
  }
}
