// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VoteProcedure$Type } from "./VoteProcedure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VoteProcedure"]: VoteProcedure$Type;
    ["contracts/procedures/Vote.sol:VoteProcedure"]: VoteProcedure$Type;
  }

  interface ContractTypesMap {
    ["VoteProcedure"]: GetContractReturnType<VoteProcedure$Type["abi"]>;
    ["contracts/procedures/Vote.sol:VoteProcedure"]: GetContractReturnType<VoteProcedure$Type["abi"]>;
  }
}
