// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Create2$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Create2",
  "sourceName": "@openzeppelin/contracts/utils/Create2.sol",
  "abi": [
    {
      "inputs": [],
      "name": "Create2EmptyBytecode",
      "type": "error"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200306fde230a8ada96ab973b1e3be4f097796175fec3803ea7c83e7102a8f00bb64736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200306fde230a8ada96ab973b1e3be4f097796175fec3803ea7c83e7102a8f00bb64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Create2",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Create2.sol:Create2",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Create2",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Create2$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Create2.sol:Create2",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Create2$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Create2",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Create2.sol:Create2",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Create2$Type["abi"]>>;
}
