// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { GsnTypes$Type } from './GsnTypes'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['GsnTypes']: GsnTypes$Type;
    ['@opengsn/contracts/src/utils/GsnTypes.sol:GsnTypes']: GsnTypes$Type;
  }

  interface ContractTypesMap {
    ['GsnTypes']: GetContractReturnType<GsnTypes$Type['abi']>;
    ['@opengsn/contracts/src/utils/GsnTypes.sol:GsnTypes']: GetContractReturnType<GsnTypes$Type['abi']>;
  }
}
