// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from 'viem'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'
import '@nomicfoundation/hardhat-viem/types'

export interface GsnTypes$Type {
  _format: 'hh-sol-artifact-1',
  contractName: 'GsnTypes',
  sourceName: '@opengsn/contracts/src/utils/GsnTypes.sol',
  abi: [],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {}
}

declare module '@nomicfoundation/hardhat-viem/types' {
  export function deployContract (
    contractName: 'GsnTypes',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<GsnTypes$Type['abi']>>
  export function deployContract (
    contractName: '@opengsn/contracts/src/utils/GsnTypes.sol:GsnTypes',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<GsnTypes$Type['abi']>>

  export function sendDeploymentTransaction (
    contractName: 'GsnTypes',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<GsnTypes$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>
  export function sendDeploymentTransaction (
    contractName: '@opengsn/contracts/src/utils/GsnTypes.sol:GsnTypes',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<GsnTypes$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>

  export function getContractAt (
    contractName: 'GsnTypes',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<GsnTypes$Type['abi']>>
  export function getContractAt (
    contractName: '@opengsn/contracts/src/utils/GsnTypes.sol:GsnTypes',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<GsnTypes$Type['abi']>>
}
