// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IERC777Recipient$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IERC777Recipient",
  "sourceName": "@openzeppelin/contracts/interfaces/IERC777Recipient.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "operator",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "from",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        },
        {
          "internalType": "bytes",
          "name": "userData",
          "type": "bytes"
        },
        {
          "internalType": "bytes",
          "name": "operatorData",
          "type": "bytes"
        }
      ],
      "name": "tokensReceived",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IERC777Recipient",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC777Recipient$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/interfaces/IERC777Recipient.sol:IERC777Recipient",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC777Recipient$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IERC777Recipient",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC777Recipient$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/interfaces/IERC777Recipient.sol:IERC777Recipient",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC777Recipient$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IERC777Recipient",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC777Recipient$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/interfaces/IERC777Recipient.sol:IERC777Recipient",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC777Recipient$Type["abi"]>>;
}
