// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Comparators$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Comparators",
  "sourceName": "@openzeppelin/contracts/utils/Comparators.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c119f65e5c34881ee703de0146c2e7546202f213a732b952365d7a1bee5465c564736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c119f65e5c34881ee703de0146c2e7546202f213a732b952365d7a1bee5465c564736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Comparators",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Comparators$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Comparators.sol:Comparators",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Comparators$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Comparators",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Comparators$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Comparators.sol:Comparators",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Comparators$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Comparators",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Comparators$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Comparators.sol:Comparators",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Comparators$Type["abi"]>>;
}
