// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CoreLibrary$Type } from "./CoreLibrary";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CoreLibrary"]: CoreLibrary$Type;
    ["contracts/libraries/CoreLibrary.sol:CoreLibrary"]: CoreLibrary$Type;
  }

  interface ContractTypesMap {
    ["CoreLibrary"]: GetContractReturnType<CoreLibrary$Type["abi"]>;
    ["contracts/libraries/CoreLibrary.sol:CoreLibrary"]: GetContractReturnType<CoreLibrary$Type["abi"]>;
  }
}
