// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CoreLibrary$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CoreLibrary",
  "sourceName": "contracts/libraries/CoreLibrary.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d8506a6ebb8e2befcc5217b8c8b1dd6b106f05ac1717c6df1baa4f899bf1594464736f6c63430008130033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d8506a6ebb8e2befcc5217b8c8b1dd6b106f05ac1717c6df1baa4f899bf1594464736f6c63430008130033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "CoreLibrary",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "CoreLibrary",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibrary$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibrary$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "CoreLibrary",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
}
