// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CoreLibrary$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CoreLibrary",
  "sourceName": "contracts/libraries/CoreLibrary.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a373b321462910ff2ad29e76ac6c38d37767b7536949c2d61ac629b60497b6b864736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a373b321462910ff2ad29e76ac6c38d37767b7536949c2d61ac629b60497b6b864736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "CoreLibrary",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "CoreLibrary",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibrary$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibrary$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "CoreLibrary",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
}
