// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CoreLibrary$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CoreLibrary",
  "sourceName": "contracts/libraries/CoreLibrary.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220099e3cb6b94b376e62ee666875abf85a20c32c88d27ce76277b4693855b6592e64736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220099e3cb6b94b376e62ee666875abf85a20c32c88d27ce76277b4693855b6592e64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "CoreLibrary",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "CoreLibrary",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibrary$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibrary$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "CoreLibrary",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/CoreLibrary.sol:CoreLibrary",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibrary$Type["abi"]>>;
}
