// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OrganLibrary$Type } from "./OrganLibrary";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OrganLibrary"]: OrganLibrary$Type;
    ["contracts/libraries/OrganLibrary.sol:OrganLibrary"]: OrganLibrary$Type;
  }

  interface ContractTypesMap {
    ["OrganLibrary"]: GetContractReturnType<OrganLibrary$Type["abi"]>;
    ["contracts/libraries/OrganLibrary.sol:OrganLibrary"]: GetContractReturnType<OrganLibrary$Type["abi"]>;
  }
}
