// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { IERC2771Recipient$Type } from './IERC2771Recipient'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['IERC2771Recipient']: IERC2771Recipient$Type;
    ['@opengsn/contracts/src/interfaces/IERC2771Recipient.sol:IERC2771Recipient']: IERC2771Recipient$Type;
  }

  interface ContractTypesMap {
    ['IERC2771Recipient']: GetContractReturnType<IERC2771Recipient$Type['abi']>;
    ['@opengsn/contracts/src/interfaces/IERC2771Recipient.sol:IERC2771Recipient']: GetContractReturnType<IERC2771Recipient$Type['abi']>;
  }
}
