// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from 'viem'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'
import '@nomicfoundation/hardhat-viem/types'

export interface IERC2771Recipient$Type {
  _format: 'hh-sol-artifact-1',
  contractName: 'IERC2771Recipient',
  sourceName: '@opengsn/contracts/src/interfaces/IERC2771Recipient.sol',
  abi: [
    {
      inputs: [
        {
          internalType: 'address',
          name: 'forwarder',
          type: 'address'
        }
      ],
      name: 'isTrustedForwarder',
      outputs: [
        {
          internalType: 'bool',
          name: '',
          type: 'bool'
        }
      ],
      stateMutability: 'view',
      type: 'function'
    }
  ],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {}
}

declare module '@nomicfoundation/hardhat-viem/types' {
  export function deployContract (
    contractName: 'IERC2771Recipient',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC2771Recipient$Type['abi']>>
  export function deployContract (
    contractName: '@opengsn/contracts/src/interfaces/IERC2771Recipient.sol:IERC2771Recipient',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC2771Recipient$Type['abi']>>

  export function sendDeploymentTransaction (
    contractName: 'IERC2771Recipient',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC2771Recipient$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>
  export function sendDeploymentTransaction (
    contractName: '@opengsn/contracts/src/interfaces/IERC2771Recipient.sol:IERC2771Recipient',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC2771Recipient$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>

  export function getContractAt (
    contractName: 'IERC2771Recipient',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC2771Recipient$Type['abi']>>
  export function getContractAt (
    contractName: '@opengsn/contracts/src/interfaces/IERC2771Recipient.sol:IERC2771Recipient',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC2771Recipient$Type['abi']>>
}
