// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ProcedureLibrary$Type } from "./ProcedureLibrary";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ProcedureLibrary"]: ProcedureLibrary$Type;
    ["contracts/libraries/ProcedureLibrary.sol:ProcedureLibrary"]: ProcedureLibrary$Type;
  }

  interface ContractTypesMap {
    ["ProcedureLibrary"]: GetContractReturnType<ProcedureLibrary$Type["abi"]>;
    ["contracts/libraries/ProcedureLibrary.sol:ProcedureLibrary"]: GetContractReturnType<ProcedureLibrary$Type["abi"]>;
  }
}
