// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC777Sender$Type } from "./IERC777Sender";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC777Sender"]: IERC777Sender$Type;
    ["@openzeppelin/contracts/interfaces/IERC777Sender.sol:IERC777Sender"]: IERC777Sender$Type;
  }

  interface ContractTypesMap {
    ["IERC777Sender"]: GetContractReturnType<IERC777Sender$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC777Sender.sol:IERC777Sender"]: GetContractReturnType<IERC777Sender$Type["abi"]>;
  }
}
