// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { MinLibBytes$Type } from './MinLibBytes'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['MinLibBytes']: MinLibBytes$Type;
    ['@opengsn/contracts/src/utils/MinLibBytes.sol:MinLibBytes']: MinLibBytes$Type;
  }

  interface ContractTypesMap {
    ['MinLibBytes']: GetContractReturnType<MinLibBytes$Type['abi']>;
    ['@opengsn/contracts/src/utils/MinLibBytes.sol:MinLibBytes']: GetContractReturnType<MinLibBytes$Type['abi']>;
  }
}
