// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from 'viem'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'
import '@nomicfoundation/hardhat-viem/types'

export interface MinLibBytes$Type {
  _format: 'hh-sol-artifact-1',
  contractName: 'MinLibBytes',
  sourceName: '@opengsn/contracts/src/utils/MinLibBytes.sol',
  abi: [],
  bytecode: '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f86d6763d11dc7f3aba4efabd47288168ad7130ffe82d3238fed46e1f845342864736f6c63430008130033',
  deployedBytecode: '0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f86d6763d11dc7f3aba4efabd47288168ad7130ffe82d3238fed46e1f845342864736f6c63430008130033',
  linkReferences: {},
  deployedLinkReferences: {}
}

declare module '@nomicfoundation/hardhat-viem/types' {
  export function deployContract (
    contractName: 'MinLibBytes',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MinLibBytes$Type['abi']>>
  export function deployContract (
    contractName: '@opengsn/contracts/src/utils/MinLibBytes.sol:MinLibBytes',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MinLibBytes$Type['abi']>>

  export function sendDeploymentTransaction (
    contractName: 'MinLibBytes',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MinLibBytes$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>
  export function sendDeploymentTransaction (
    contractName: '@opengsn/contracts/src/utils/MinLibBytes.sol:MinLibBytes',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MinLibBytes$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>

  export function getContractAt (
    contractName: 'MinLibBytes',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MinLibBytes$Type['abi']>>
  export function getContractAt (
    contractName: '@opengsn/contracts/src/utils/MinLibBytes.sol:MinLibBytes',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MinLibBytes$Type['abi']>>
}
