// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SlotDerivation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SlotDerivation",
  "sourceName": "@openzeppelin/contracts/utils/SlotDerivation.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220d3610fbb417a2658ee29f74495dad1ffabef13ada1d6662e77873fc0db48b04264736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220d3610fbb417a2658ee29f74495dad1ffabef13ada1d6662e77873fc0db48b04264736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
}
