// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Procedure$Type } from "./Procedure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Procedure"]: Procedure$Type;
    ["contracts/Procedure.sol:Procedure"]: Procedure$Type;
  }

  interface ContractTypesMap {
    ["Procedure"]: GetContractReturnType<Procedure$Type["abi"]>;
    ["contracts/Procedure.sol:Procedure"]: GetContractReturnType<Procedure$Type["abi"]>;
  }
}
