// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface StorageSlot$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "StorageSlot",
  "sourceName": "@openzeppelin/contracts/utils/StorageSlot.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212203a02447ab2775118508cdf6f94420ce4aca7a929746e7da535ea7a59f3407b9364736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212203a02447ab2775118508cdf6f94420ce4aca7a929746e7da535ea7a59f3407b9364736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "StorageSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "StorageSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StorageSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StorageSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "StorageSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
}
