// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ECDSA$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ECDSA",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/ECDSA.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ECDSAInvalidSignature",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "length",
          "type": "uint256"
        }
      ],
      "name": "ECDSAInvalidSignatureLength",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "s",
          "type": "bytes32"
        }
      ],
      "name": "ECDSAInvalidSignatureS",
      "type": "error"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207d831ed31e57cbf22debfdd2aa526375d5a7f96c56a8e71fdc716acc2c58e1c564736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207d831ed31e57cbf22debfdd2aa526375d5a7f96c56a8e71fdc716acc2c58e1c564736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ECDSA",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ECDSA",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ECDSA$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ECDSA$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ECDSA",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ECDSA$Type["abi"]>>;
}
