// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { IERC1820Registry$Type } from './IERC1820Registry'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['IERC1820Registry']: IERC1820Registry$Type;
    ['@openzeppelin/contracts/utils/introspection/IERC1820Registry.sol:IERC1820Registry']: IERC1820Registry$Type;
  }

  interface ContractTypesMap {
    ['IERC1820Registry']: GetContractReturnType<IERC1820Registry$Type['abi']>;
    ['@openzeppelin/contracts/utils/introspection/IERC1820Registry.sol:IERC1820Registry']: GetContractReturnType<IERC1820Registry$Type['abi']>;
  }
}
