// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { IForwarder$Type } from './IForwarder'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['IForwarder']: IForwarder$Type;
    ['@opengsn/contracts/src/forwarder/IForwarder.sol:IForwarder']: IForwarder$Type;
  }

  interface ContractTypesMap {
    ['IForwarder']: GetContractReturnType<IForwarder$Type['abi']>;
    ['@opengsn/contracts/src/forwarder/IForwarder.sol:IForwarder']: GetContractReturnType<IForwarder$Type['abi']>;
  }
}
