// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from 'viem'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'
import '@nomicfoundation/hardhat-viem/types'

export interface IForwarder$Type {
  _format: 'hh-sol-artifact-1',
  contractName: 'IForwarder',
  sourceName: '@opengsn/contracts/src/forwarder/IForwarder.sol',
  abi: [
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'bytes32',
          name: 'domainSeparator',
          type: 'bytes32'
        },
        {
          indexed: false,
          internalType: 'bytes',
          name: 'domainValue',
          type: 'bytes'
        }
      ],
      name: 'DomainRegistered',
      type: 'event'
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'bytes32',
          name: 'typeHash',
          type: 'bytes32'
        },
        {
          indexed: false,
          internalType: 'string',
          name: 'typeStr',
          type: 'string'
        }
      ],
      name: 'RequestTypeRegistered',
      type: 'event'
    },
    {
      inputs: [
        {
          components: [
            {
              internalType: 'address',
              name: 'from',
              type: 'address'
            },
            {
              internalType: 'address',
              name: 'to',
              type: 'address'
            },
            {
              internalType: 'uint256',
              name: 'value',
              type: 'uint256'
            },
            {
              internalType: 'uint256',
              name: 'gas',
              type: 'uint256'
            },
            {
              internalType: 'uint256',
              name: 'nonce',
              type: 'uint256'
            },
            {
              internalType: 'bytes',
              name: 'data',
              type: 'bytes'
            },
            {
              internalType: 'uint256',
              name: 'validUntilTime',
              type: 'uint256'
            }
          ],
          internalType: 'struct IForwarder.ForwardRequest',
          name: 'forwardRequest',
          type: 'tuple'
        },
        {
          internalType: 'bytes32',
          name: 'domainSeparator',
          type: 'bytes32'
        },
        {
          internalType: 'bytes32',
          name: 'requestTypeHash',
          type: 'bytes32'
        },
        {
          internalType: 'bytes',
          name: 'suffixData',
          type: 'bytes'
        },
        {
          internalType: 'bytes',
          name: 'signature',
          type: 'bytes'
        }
      ],
      name: 'execute',
      outputs: [
        {
          internalType: 'bool',
          name: 'success',
          type: 'bool'
        },
        {
          internalType: 'bytes',
          name: 'ret',
          type: 'bytes'
        }
      ],
      stateMutability: 'payable',
      type: 'function'
    },
    {
      inputs: [
        {
          internalType: 'address',
          name: 'from',
          type: 'address'
        }
      ],
      name: 'getNonce',
      outputs: [
        {
          internalType: 'uint256',
          name: '',
          type: 'uint256'
        }
      ],
      stateMutability: 'view',
      type: 'function'
    },
    {
      inputs: [
        {
          internalType: 'string',
          name: 'name',
          type: 'string'
        },
        {
          internalType: 'string',
          name: 'version',
          type: 'string'
        }
      ],
      name: 'registerDomainSeparator',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    },
    {
      inputs: [
        {
          internalType: 'string',
          name: 'typeName',
          type: 'string'
        },
        {
          internalType: 'string',
          name: 'typeSuffix',
          type: 'string'
        }
      ],
      name: 'registerRequestType',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    },
    {
      inputs: [
        {
          internalType: 'bytes4',
          name: 'interfaceId',
          type: 'bytes4'
        }
      ],
      name: 'supportsInterface',
      outputs: [
        {
          internalType: 'bool',
          name: '',
          type: 'bool'
        }
      ],
      stateMutability: 'view',
      type: 'function'
    },
    {
      inputs: [
        {
          components: [
            {
              internalType: 'address',
              name: 'from',
              type: 'address'
            },
            {
              internalType: 'address',
              name: 'to',
              type: 'address'
            },
            {
              internalType: 'uint256',
              name: 'value',
              type: 'uint256'
            },
            {
              internalType: 'uint256',
              name: 'gas',
              type: 'uint256'
            },
            {
              internalType: 'uint256',
              name: 'nonce',
              type: 'uint256'
            },
            {
              internalType: 'bytes',
              name: 'data',
              type: 'bytes'
            },
            {
              internalType: 'uint256',
              name: 'validUntilTime',
              type: 'uint256'
            }
          ],
          internalType: 'struct IForwarder.ForwardRequest',
          name: 'forwardRequest',
          type: 'tuple'
        },
        {
          internalType: 'bytes32',
          name: 'domainSeparator',
          type: 'bytes32'
        },
        {
          internalType: 'bytes32',
          name: 'requestTypeHash',
          type: 'bytes32'
        },
        {
          internalType: 'bytes',
          name: 'suffixData',
          type: 'bytes'
        },
        {
          internalType: 'bytes',
          name: 'signature',
          type: 'bytes'
        }
      ],
      name: 'verify',
      outputs: [],
      stateMutability: 'view',
      type: 'function'
    }
  ],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {}
}

declare module '@nomicfoundation/hardhat-viem/types' {
  export function deployContract (
    contractName: 'IForwarder',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IForwarder$Type['abi']>>
  export function deployContract (
    contractName: '@opengsn/contracts/src/forwarder/IForwarder.sol:IForwarder',
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IForwarder$Type['abi']>>

  export function sendDeploymentTransaction (
    contractName: 'IForwarder',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IForwarder$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>
  export function sendDeploymentTransaction (
    contractName: '@opengsn/contracts/src/forwarder/IForwarder.sol:IForwarder',
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IForwarder$Type['abi']>;
    deploymentTransaction: GetTransactionReturnType;
  }>

  export function getContractAt (
    contractName: 'IForwarder',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IForwarder$Type['abi']>>
  export function getContractAt (
    contractName: '@opengsn/contracts/src/forwarder/IForwarder.sol:IForwarder',
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IForwarder$Type['abi']>>
}
