// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EnumerableSet$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EnumerableSet",
  "sourceName": "@openzeppelin/contracts/utils/structs/EnumerableSet.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220a52bb16444c8791e7b3996c37939aff0cd56bffdb5d17458d2d9f76e2685316664736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220a52bb16444c8791e7b3996c37939aff0cd56bffdb5d17458d2d9f76e2685316664736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EnumerableSet",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableSet.sol:EnumerableSet",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EnumerableSet",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EnumerableSet$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableSet.sol:EnumerableSet",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EnumerableSet$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EnumerableSet",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/structs/EnumerableSet.sol:EnumerableSet",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EnumerableSet$Type["abi"]>>;
}
