// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20VoteProcedure$Type } from "./ERC20VoteProcedure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20VoteProcedure"]: ERC20VoteProcedure$Type;
    ["contracts/procedures/ERC20Vote.sol:ERC20VoteProcedure"]: ERC20VoteProcedure$Type;
  }

  interface ContractTypesMap {
    ["ERC20VoteProcedure"]: GetContractReturnType<ERC20VoteProcedure$Type["abi"]>;
    ["contracts/procedures/ERC20Vote.sol:ERC20VoteProcedure"]: GetContractReturnType<ERC20VoteProcedure$Type["abi"]>;
  }
}
