// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleCollectible$Type } from "./ExampleCollectible";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleCollectible"]: ExampleCollectible$Type;
    ["contracts/utils/ExampleCollectible.sol:ExampleCollectible"]: ExampleCollectible$Type;
  }

  interface ContractTypesMap {
    ["ExampleCollectible"]: GetContractReturnType<ExampleCollectible$Type["abi"]>;
    ["contracts/utils/ExampleCollectible.sol:ExampleCollectible"]: GetContractReturnType<ExampleCollectible$Type["abi"]>;
  }
}
