// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import 'hardhat/types/artifacts'
import type { GetContractReturnType } from '@nomicfoundation/hardhat-viem/types'

import { GsnEip712Library$Type } from './GsnEip712Library'

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['GsnEip712Library']: GsnEip712Library$Type;
    ['@opengsn/contracts/src/utils/GsnEip712Library.sol:GsnEip712Library']: GsnEip712Library$Type;
  }

  interface ContractTypesMap {
    ['GsnEip712Library']: GetContractReturnType<GsnEip712Library$Type['abi']>;
    ['@opengsn/contracts/src/utils/GsnEip712Library.sol:GsnEip712Library']: GetContractReturnType<GsnEip712Library$Type['abi']>;
  }
}
