// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OrganigramClient$Type } from "./OrganigramClient";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OrganigramClient"]: OrganigramClient$Type;
    ["contracts/OrganigramClient.sol:OrganigramClient"]: OrganigramClient$Type;
  }

  interface ContractTypesMap {
    ["OrganigramClient"]: GetContractReturnType<OrganigramClient$Type["abi"]>;
    ["contracts/OrganigramClient.sol:OrganigramClient"]: GetContractReturnType<OrganigramClient$Type["abi"]>;
  }
}
