// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Clones$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Clones",
  "sourceName": "@openzeppelin/contracts/proxy/Clones.sol",
  "abi": [
    {
      "inputs": [],
      "name": "CloneArgumentsTooLong",
      "type": "error"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200b4a33d8948e0a3a9b4e4ecea1e2642511bde55fb477ed2b948847f733c7419564736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212200b4a33d8948e0a3a9b4e4ecea1e2642511bde55fb477ed2b948847f733c7419564736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Clones",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Clones",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Clones$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Clones$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Clones",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/proxy/Clones.sol:Clones",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Clones$Type["abi"]>>;
}
