// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Organ$Type } from "./Organ";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Organ"]: Organ$Type;
    ["contracts/Organ.sol:Organ"]: Organ$Type;
  }

  interface ContractTypesMap {
    ["Organ"]: GetContractReturnType<Organ$Type["abi"]>;
    ["contracts/Organ.sol:Organ"]: GetContractReturnType<Organ$Type["abi"]>;
  }
}
