// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAsset$Type } from "./IAsset";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAsset"]: IAsset$Type;
    ["contracts/IAsset.sol:IAsset"]: IAsset$Type;
  }

  interface ContractTypesMap {
    ["IAsset"]: GetContractReturnType<IAsset$Type["abi"]>;
    ["contracts/IAsset.sol:IAsset"]: GetContractReturnType<IAsset$Type["abi"]>;
  }
}
