// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleMultitoken$Type } from "./ExampleMultitoken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleMultitoken"]: ExampleMultitoken$Type;
    ["contracts/utils/ExampleMultitoken.sol:ExampleMultitoken"]: ExampleMultitoken$Type;
  }

  interface ContractTypesMap {
    ["ExampleMultitoken"]: GetContractReturnType<ExampleMultitoken$Type["abi"]>;
    ["contracts/utils/ExampleMultitoken.sol:ExampleMultitoken"]: GetContractReturnType<ExampleMultitoken$Type["abi"]>;
  }
}
