// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ExampleCoin$Type } from "./ExampleCoin";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ExampleCoin"]: ExampleCoin$Type;
    ["contracts/utils/ExampleCoin.sol:ExampleCoin"]: ExampleCoin$Type;
  }

  interface ContractTypesMap {
    ["ExampleCoin"]: GetContractReturnType<ExampleCoin$Type["abi"]>;
    ["contracts/utils/ExampleCoin.sol:ExampleCoin"]: GetContractReturnType<ExampleCoin$Type["abi"]>;
  }
}
