// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Errors$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Errors",
  "sourceName": "@openzeppelin/contracts/utils/Errors.sol",
  "abi": [
    {
      "inputs": [],
      "name": "FailedCall",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "FailedDeployment",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "balance",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "needed",
          "type": "uint256"
        }
      ],
      "name": "InsufficientBalance",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "name": "MissingPrecompile",
      "type": "error"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220a4e4c47d0ebde91059bed78cf86e0f54d79113e7858704cf578b0eeea8393b1164736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220a4e4c47d0ebde91059bed78cf86e0f54d79113e7858704cf578b0eeea8393b1164736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Errors",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Errors.sol:Errors",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Errors",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Errors$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Errors.sol:Errors",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Errors$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Errors",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Errors.sol:Errors",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Errors$Type["abi"]>>;
}
